// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   float64
	Currency  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Entry struct {
	ID        int64
	AccountID pgtype.Int8
	// Can be negative or positive
	Amount    float64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// Must be positive
	Amount    float64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
